### PR TITLE
Fix up construct-2.9 dependencies

### PR DESCRIPTION
**Pull request by ikelos**
Sorry, messed up the setup.py dependencies.  5:S  Hopefully won't be too many other bits that haven't been exercised since the changes, but happy to fix them up (as long as you're happy with merge requests for them)...  5:)

### CODE REVIEW

**Comment by moyix** [comment]
Yup, definitely happy to merge other things you find!

**Comment by ikelos** [comment]
Cool, I'll just keep putting any changes I find here and then when it calms down we can push it (mebbe next week sometime?).  5:)  Thanks!

**Comment by ikelos** [comment]
Spotted an issue when I converted String to PaddedString.  It's still present in IMAGE_SECTION_HEADER.Name, but I think that will always work out as utf8 rather than utf16 as was used in the GUID conversion.  Probably worth pulling at this point (since it does break parsing of certain PDBs depending on their GUID) and then I can do another pull request if anything else major crops up.  5:)

**Comment by moyix** [comment]
Cool, I'll pull these in :) Thanks again for the updates!

**Pull request merged**
